services:
  odoo:
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - RUNNING_ENV=$ENV
      - MARABUNTA_MODE=demo
      - DB_HOST=$PGHOST
      - DB_NAME=$PGDATABASE
      - DB_USER=$PGUSER
      - DB_PASS=$PGPASSWORD
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons,/odoo/src/addons,/odoo/external-src/web
    hostname: ${ENV}-${COMPOSE_PROJECT_NAME}
    labels:
      docky.main.service: true
      docky.user: odoo
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
version: '3.7'
